### add-tier

POST http://localhost:4567/add-tier
Accept: application/json

{
  "jexl_expression": "data.foo > 5"
}

### remove-tier

POST http://localhost:4567/remove-tier
Accept: application/json

### info

GET http://localhost:4567/info
Accept: application/json


### offsets

GET http://localhost:4567/offsets
Accept: application/json